import os

from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)

from reportlab.lib import colors

from reportlab.lib.styles import getSampleStyleSheet

styles = getSampleStyleSheet()


def generate_report(data):

    os.makedirs("generated_reports", exist_ok=True)

    filename = f"generated_reports/report_{data['id']}.pdf"

    pdf = SimpleDocTemplate(filename)

    elements = []

    # -------------------- Title --------------------

    title = Paragraph(
        "<font size='22'><b>AI Infrastructure Crack Detection</b></font>",
        styles["Title"]
    )

    subtitle = Paragraph(
        "<font size='16'>Inspection Report</font>",
        styles["Heading2"]
    )

    elements.append(title)
    elements.append(subtitle)
    elements.append(Spacer(1, 20))

    # -------------------- Report Info --------------------

    report_info = [

        ["Report ID", data.get("id", "N/A")],

        ["Generated On", datetime.now().strftime("%d %B %Y %I:%M %p")]

    ]

    info_table = Table(report_info, colWidths=[150, 250])

    info_table.setStyle(TableStyle([

        ("GRID", (0,0), (-1,-1), 1, colors.grey),

        ("BACKGROUND", (0,0), (0,-1), colors.lightgrey),

        ("BOTTOMPADDING", (0,0), (-1,-1), 8),

        ("TOPPADDING", (0,0), (-1,-1), 8),

        ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold")

    ]))

    elements.append(info_table)

    elements.append(Spacer(1,20))

    # -------------------- Image --------------------

    if os.path.exists(data["image_path"]):

        image = Image(
            data["image_path"],
            width=280,
            height=200
        )

        elements.append(image)

        elements.append(Spacer(1,20))

    # -------------------- Details --------------------

    details = [

        ["Image Name", data["filename"]],

        ["Prediction", data["prediction"]],

        ["Confidence", f"{data['confidence']} %"],

        ["Structure", data["structure"]],

        ["Model", data["model_name"]],

        ["Inspection Status", "Completed"]

    ]

    table = Table(details, colWidths=[150,250])

    table.setStyle(TableStyle([

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#D6EAF8")),

        ("BOTTOMPADDING",(0,0),(-1,-1),10),

        ("TOPPADDING",(0,0),(-1,-1),10),

        ("FONTNAME",(0,0),(-1,-1),"Helvetica")

    ]))

    elements.append(table)

    elements.append(Spacer(1,20))

    # -------------------- Remarks --------------------

    remarks = "No crack detected. No immediate maintenance required."

    if data["prediction"] == "Crack":

        remarks = (
            "Crack detected. Immediate physical inspection "
            "and preventive maintenance are recommended."
        )

    elements.append(

        Paragraph(

            f"<b>Remarks:</b> {remarks}",

            styles["BodyText"]

        )

    )

    elements.append(Spacer(1,20))

    # -------------------- Disclaimer --------------------

    elements.append(

        Paragraph(

            "<b>Disclaimer:</b> This report is generated automatically "
            "using an AI model and should be verified by a qualified engineer.",

            styles["Italic"]

        )

    )

    elements.append(Spacer(1,40))

    # -------------------- Signature --------------------

    elements.append(

        Paragraph(

            "<b>Inspector Signature</b>",

            styles["Normal"]

        )

    )

    elements.append(Spacer(1,25))

    elements.append(

        Paragraph(

            "______________________________",

            styles["Normal"]

        )

    )

    elements.append(Spacer(1,30))

    # -------------------- Footer --------------------

    footer = Paragraph(

        "<font size='10'><b>Generated by AI Infrastructure Crack Detection Platform</b></font>",

        styles["Normal"]

    )

    elements.append(footer)

    pdf.build(elements)

    return filename